### ISSUE TITLE
Allow swplive attribute on container

### ISSUE THREAD

**Issue by verygoodplugins** [jchristopher/searchwp-live-ajax-search#110]
This falls into the "would be nice" category....

Both Elementor and Beaver Builder allow adding data attributes via the visual editor, but attributes are added to the parent container.

So in the case of the search form they aren't added to the actual `input`, and SearchWP can't be initialized without adding custom code.

Would be awesome if in searchwp-live-ajax-search.js there could be a 

`jQuery('*[data-swplive="true"] input').searchwp_live_search();`

in addition to targeting the actual input. Then we could initialize SearchWP on any search form added via these page builders (and probably others)

**Comment by jchristopher** [comment]
As it stands you can actually fire `jQuery('*[data-swplive="true"] input').searchwp_live_search();` in your theme's JS on load and you should be all set! 👍

**Comment by verygoodplugins** [comment]
I've done that. It works.

I was throwing it out there as a feature because I think there is a pool of potential customers who are using one of these popular page builders / "theme-less" themes and don't necessarily understand how to create a child theme, register a custom JS file, and add the code.

Would be an easy change to make in SWP and then you could advertise compatibility with these builders :)
