### ISSUE TITLE
bundle.js error

### ISSUE THREAD

**Issue by umpire274** [jchristopher/searchwp-live-ajax-search#111]
Hi.

I've installed SearchWP Live Ajax Search rel. 1.4.3 and enabled succeffully on my website.

But when I go to my homepage obtain an error on inspection console like this:

_`bundle.min.js?ver=1.4.3:4 Uncaught TypeError: jQuery(...).searchwp_live_search is not a function`_

I've attached also an image with the error.

Can you help me?

Alex.

![jquery_error-searchwp_live_search](https://user-images.githubusercontent.com/340183/64684872-3025ca80-d486-11e9-93ec-391b007935b6.png)

**Comment by jchristopher** [comment]
Can you send a direct link to the page that outputs those errors? Thank you!

**Comment by umpire274** [comment]
Sorry for delay. Some trouble with my email.
You can see the error in this URL

https://www.asi.it/

using 'Inspect element' -> 'Console'

Thanks.

**Comment by robertirish** [comment]
I am having the same issue—site http://blackbird.vc

**Comment by jchristopher** [comment]
Unfortunately I haven't been able to replicate this issue on my end, but I have rebuilt the bundle and tagged `1.4.3.1` if you can try that version please and let me know if it resolves the issue:

https://github.com/jchristopher/searchwp-live-ajax-search/releases/tag/1.4.3.1

There is a zip download link there, you can download and extract the zip and then overwrite the contents of your `~/wp-content/plugins/searchwp-live-ajax-search` with the contents from the zip.

Note that when you download the zip GitHub will name the folder `searchwp-live-ajax-search-1.4.3.1` but your installation will have the folder name as `searchwp-live-ajax-search`

**Comment by umpire274** [comment]
Hi Jon.

This version (1.4.3.1) solved for me the error above.

Thanks,
Alex.

**Comment by jchristopher** [comment]
Great, thank you Alex, I'll get a proper release on .org shortly. I have to imagine it was some sort of issue with the bundling process.

**Comment by jchristopher** [comment]
Version `1.4.4` is now available through automatic update from wordpress.org with the new JavaScript bundle which resolves this issue. Thank you!

**Comment by jchristopher** [comment]
After some additional conversation with @umpire274 via email, we have discovered that there were two versions of jQuery being output on the page. The first one was WordPress' version of jQuery, and SearchWP Live Ajax Search was integrating with that version. The second version was included later and overriding that core version of jQuery and as a result SearchWP Live Ajax Search was not able to integrate with that second version of jQuery.

The resolution would be to ensure that you are dequeueing the WordPress core version of jQuery if you are using a custom version, ensuring that only one version of jQuery is output on the page.

**Comment by umpire274** [comment]
Hi all. Confirm what Jon wrote above and add my hint.

To goal the suggestion it is possible to use this code (and edit for your needs) into your functions.php, if you have a custom theme installed:

```
function your_theme_include_custom_jquery() {

   wp_deregister_script('jquery');
   wp_enqueue_script('jquery', 'https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js', array(), null, true);

}
add_action('wp_enqueue_scripts', 'your_theme_include_custom_jquery');
```

Hope this help.

Bye,
Alex.
