### ISSUE TITLE
Limit Search to Specific Custom Post Type

### ISSUE THREAD

**Issue by josephbuarao** [jchristopher/searchwp-live-ajax-search#113]
Hi @jchristopher ,

I would like to filter the search result in a specific custom post type. I used these codes but it wasn't working. Could you please take a look and let me know what's wrong? 

`
     
    function my_searchwp_swp_query_args( $args ) {
    // customize $args as per https://searchwp.com/docs/swp_query/
    $swp_query = new SWP_Query(
        array(
            'engine' => 'default',      // engine to use
            'post_type' => array('agents')     // override enabled post types in engine config (SearchWP 2.7+)
        )
    );

    if ( ! empty( $swp_query->posts ) ) {
        foreach( $swp_query->posts as $post ) : setup_postdata( $post ); ?>
            <div class="search-result">
                <h3><a href="<?php echo get_permalink(); ?>"><?php the_title(); ?></a></h3>
                <?php the_excerpt(); ?>
            </div>
        <?php endforeach; wp_reset_postdata();
    } else {
        ?><p>No results found.</p><?php
    }

    return $args;
  }

  add_filter( 'searchwp_swp_query_args', 'my_searchwp_swp_query_args' );`

Thanks

**Comment by jchristopher** [comment]
Hi @josephbuarao — if you're just looking to filter the args, you can do this:

```php
function my_searchwp_swp_query_args( $args ) {
    $args['post_type'] = array('agents');

    return $args;
}

add_filter( 'searchwp_swp_query_args', 'my_searchwp_swp_query_args' );
```
