### ISSUE TITLE
Live search not respecting Woocommerce hidden products?

### ISSUE THREAD

**Issue by cruiseback** [jchristopher/searchwp-live-ajax-search#116]
Hi Jonathan,

Thank you for a great plugin.

We use it on our site and have a couple of hidden products for different campaigns.

We have forced Wordpress to respect them being hidden by using:
`add_action( 'pre_get_posts', 'search_query_fix' );

function search_query_fix( $query = false ) {
  if(!is_admin() && is_search()){
    $query->set( 'tax_query', array(
        array(
            'taxonomy' => 'product_visibility',
            'field'    => 'name',
            'terms'    => 'exclude-from-search',
            'operator' => 'NOT IN',
        )
    ));
  }
}`

But Live Search still shows them in the search bar although they are hidden on the search page?

Can we make Live Search respect them being hidden as well?

Thanks!

**Comment by jchristopher** [comment]
I would suggest instead using this hook:

```php
add_filter( 'searchwp_live_search_query_args', function( $args ) {
    $args['tax_query'] = [ [
        'taxonomy' => 'product_visibility',
        'field'    => 'name',
        'terms'    => 'exclude-from-search',
        'operator' => 'NOT IN',
    ] ];

    return $args;
} );```
