### ISSUE TITLE
Keyboard navigation through results no longer working

### ISSUE THREAD

**Issue by Xavvi** [jchristopher/searchwp-live-ajax-search#117]
Hello,

When I first installed this plugin I was able to keyboard navigate through the dropdown list of results by pressing the up and down keys. But now it only lets me go to the first result. If I press down again it loses focus from the field. You can test this on [the page](https://epsomandewellfamilies.co.uk) itself by typing the letters “plu” into the search form and then pressing the down key in the results. 

Any idea why this might be happening?

Thanks for shining any light and thanks for an excellent plugin.

**Comment by jchristopher** [comment]
Hi @Xavvi — keyboard navigation is still working in my development environment. I can't say for sure why it stopped working on that specific site (perhaps some other JavaScript is being triggered) but I might suggest trying SearchWP Live Ajax Search in a fresh, standalone WordPress installation to see if you're still having the issue. If so, please let me know!
