### ISSUE TITLE
Search Results Persistent?

### ISSUE THREAD

**Issue by mstrykerME** [jchristopher/searchwp-live-ajax-search#119]
Hi there,

When I search for something, the results display, but as soon as I click outside of the search results, they disappear.

Thoughts?

Much appreciated!

**Comment by jchristopher** [comment]
Hi @mstrykerME — that is intended behavior. You can disable it by setting the `results_destroy_on_blur` to `false` in your configuration 👍

**Comment by mstrykerME** [comment]
Exactly what I was looking for!  Thanks a lot!
