### ISSUE TITLE
Search results require a double click in GeneratePress theme

### ISSUE THREAD

**Issue by verysiberian** [jchristopher/searchwp-live-ajax-search#122]
Hello! Thanks for this wonderful plugin. I've noticed an issue with the GeneratePress theme that I'm hoping may be possible to address. When using the nav bar search function, SearchWP Live Search works as expected except that the user must double click on a search result to view it. 

This is mentioned in the GeneratePress forum here:

https://generatepress.com/forums/topic/searchwp-live-search/

For a live example of this phenomenon, please click the magnifying glass icon in the nav bar on one of my sites and try searching for something relevant (e.g., funding). You will see the expected behavior in terms of live search results, but each result requires a double click for some unknown reason. 

Example site: https://aacnf.org/

Please let me know if any further information would be helpful. Thanks!

**Comment by jchristopher** [comment]
Hi there, sorry for not getting to this issue sooner. In reviewing the example site a single click appears to work. If it's still an issue please post and we can re-open. Thank you!
