### ISSUE TITLE
Translation in search result page

### ISSUE THREAD

**Issue by alexsouza1** [jchristopher/searchwp-live-ajax-search#125]
Hello,

I would like translate the message: ‘3’ search results found to my country language: portuguese, but I cant find this strings to translate in ‘loco translate’ or direct in directory, how to proced?

**Comment by Buxert** [comment]
I would also like to translate the plugin. But it seems that we can't translate the plugin on WordPress.org. @jchristopher can you make the plugin translatable? See the documentation here: https://make.wordpress.org/polyglots/handbook/tools/glotpress-translate-wordpress-org/

**Comment by jchristopher** [comment]
The text domain was updated in https://github.com/jchristopher/searchwp-live-ajax-search/commit/99fa3202c4e850cbdd8e2d1fc3993aed7d3b1d57 and will be included in the next release 👍
