### ISSUE TITLE
Spinner sometimes dissapears

### ISSUE THREAD

**Issue by RhRU** [jchristopher/searchwp-live-ajax-search#131]
Spinner disappears when you go over the minimum number of chars (so it starts searching)
and after that you add an additional char to search over.

After the results are shown (or no results) spinner reappears again.

So you can test it by: start searching when it starts to search add an additional letter. Spinner disappears

**Comment by asafm7** [comment]
Same to me. I think another case is when you type a space

**Comment by jchristopher** [comment]
I'm unable to replicate this issue but see that two people are having it. If you're able to record a video or gif to illustrate the problem that may help me replicate it. 👍 

Also of note: spaces are disregarded when it comes to executing a follow-up search.
