### ISSUE TITLE
Plugin messages visible on Google Search results

### ISSUE THREAD

**Issue by trentschaller** [jchristopher/searchwp-live-ajax-search#134]
If I search Google for my organization name, the content of the results are messages from this plugin instead of the actual content of my pages:

"When autocomplete results are available use up and down arrows to review and enter to go to the desired page. Touch device users, explore by touch or with ..."

![image](https://user-images.githubusercontent.com/2749576/86225149-22af0d80-bb8a-11ea-854f-cf967ffeef7b.png)

**Comment by jchristopher** [comment]
Thank you! The next version will revise how the ARIA attributes are set up so as to avoid the text being indexed by search engines but continue to be used as a label for the field.
