### ISSUE TITLE
Is CSS class "searchwp-highlight" not available anymore?

### ISSUE THREAD

**Issue by anyway** [jchristopher/searchwp-live-ajax-search#138]
Hi,

i made an update today (WP, searchWP, SearchWP Live Ajax Search) and now my layout in the Live Search dropdown doesn’t fit anymore.
I have looked at the new template system and basically everything is clear except for the highlighting of the search term within the dropdown.

There was a CSS class `searchwp-highlight` for this before.

Example:
`<mark class=”searchwp-highlight”>uncompleteSearc</mark>`

This class does not seem to exist anymore. Is the whole function no longer supported or am I missing something?

Thanks for your help!

**Comment by jchristopher** [comment]
Hi there, that class is added using SearchWP (not Live Ajax Search) so I would recommend opening a support ticket to get help with highlighting. Thank you!
