### ISSUE TITLE
Results element positioning breaks on window resize when multiple instances of search textbox exist

### ISSUE THREAD

**Issue by grantnorwood** [jchristopher/searchwp-live-ajax-search#16]
It seems to be that when multiple `input[data-swplive="true"]` are on the page, the results element is visible, and `window.resize()` is triggered, then the results element is instantly re-positioned relative to the last `.searchwp-live-search-results` input in the DOM instead of the active input element with your search terms.

### Test 1: One visible and one hidden live-search input element
I have 2 instances of live search on my page, one is visible in the larger desktop layout, and the other is only visible when on a mobile device.  When in my desktop layout, after typing in some search terms and with the results element visible and positioned correctly, then `window.resize()` events cause the results element to be re-positioned relative to the hidden input, which does not report position accurately so the results element is off screen. _(see mockup below)_

### Test 2: Two visible live-search input elements
Both live-search input elements are visible.  Similar to test 1, when searching using the first input, the results element appears and positions normally.  However, on `window.resize()`, the results element is instantly re-positioned relevant to the 2nd input located later in the DOM, not the currently active input with search terms. _(see mockup below)_

### Configuration
I'm using the config filter as below:

```php
/**
 * Override config. (@see https://searchwp.com/docs/extensions/live-search/)
 */
function searchwp_live_search_configs( $configs ) {

    $configs['default']['results']['width'] = 'css'; // whether the width should automatically match the input (auto|css)
    $configs['default']['results']['offset'] = array(
        'x' => -182, // x offset (in pixels)
        'y' => 8 // y offset (in pixels)
    );

    return $configs;

}
```

#### Test 1
![searchwp-live-search issue - test 1](https://cloud.githubusercontent.com/assets/707463/4437609/559e2bd0-479c-11e4-9d63-3bf8683e5c1a.png)

#### Test 2
![searchwp-live-search issue - test 2](https://cloud.githubusercontent.com/assets/707463/4437610/5adf2f4a-479c-11e4-9155-b11187e3cd34.png)

### The Fix?

If you have some guidance on how you'd like to fix this, I'm happy to do the work  :)  It seems like either there should be separate results elements shown per input element (if viewing multiple results simultaneously is desired), or otherwise ensuring the results element is positioned relative to the currently active input element, regardless of whether it is visible or hidden.

Also, I noticed in searchwp-live-search.js that `this.results_id` is never set, so it is null throughout the script and in the results element id attribute.  Could be related to this issue.

I am just now starting on a fix for this, but if you have a quick resolution on hand I'm happy to defer to you.

**Thanks for an awesome (and free) search tool!**

**Comment by jchristopher** [comment]
This is a crazy old Issue, apologies! Lost track of it — are you still having problems here?

**Comment by grantnorwood** [comment]
Not sure if the issue still exists, our latest redesign uses Typeahead.js for autocomplete  :)  Feel free to close this issue if it's not impacting any other users.

Thanks for following up!
