### ISSUE TITLE
Dequeue style not working

### ISSUE THREAD

**Issue by espellcaste** [jchristopher/searchwp-live-ajax-search#18]
A possible bug?! When I try to dequeue the search-live-search style (function below), it doesn't allow me:

wp_dequeue_style( 'searchwp-live-search' );

I first was trying to dequeue it in a custom template of mine and thought that was the issue, until I tested on latest WordPress installation with Twenty Fourteen and could confirm the issue.

The below filter works correctly.

add_filter( 'searchwp_live_search_base_styles', '__return_false' );

**Comment by espellcaste** [comment]
1.1.1 is with the same problem! :(

**Comment by jchristopher** [comment]
Sorry for the delay in commenting here. This is not a bug, it's intended behavior as per the docs https://searchwp.com/extensions/live-search/#searchwp_live_search_base_styles intent being to not add an additional HTTP request just for very common positioning.

From the [changelog](https://wordpress.org/plugins/searchwp-live-ajax-search/changelog/) the following changes were made in 1.1.1

* Fixed an issue that prevented SearchWP Supplemental engines from showing up in the Widget config
* Added French translation
* Added Serbian translation

**Comment by espellcaste** [comment]
Actually, my problem lies with this one: https://searchwp.com/extensions/live-search/#customizing-results

It is the one that doesn't want to be removed. :(
