### ISSUE TITLE
Live search does not find custom post types

### ISSUE THREAD

**Issue by TheZoker** [jchristopher/searchwp-live-ajax-search#21]
I search for a word, but the live search does show "No results", when I press enter and search for the term (so ?s=term) it shows results.

Can you help me to fix this?

Thank you

**Comment by joemcgill** [comment]
I'm experiencing this issue as well. In order to get live search results for custom post types, you need to remove the `'_builtin' => true,` argument, which will limit search results to only post types that are default to WordPress, i.e., post, page, and attachement.

**Comment by jchristopher** [comment]
Great point, I'm going to reopen this issue to remember to remove that argument from the defaults.

**Comment by TheZoker** [comment]
Could you may add a setting for that in the backend? Would make it much easier for non phpers to understand

**Comment by jchristopher** [comment]
I don't intend to add a settings page at all as the hooks in place take care of it all. The exact code to remove that argument (that you can use right now) would be:

```php
function searchwp_live_search_query_args( $args ) {
    if ( isset( $args['_builtin'] ) ) {
        unset( $args['_builtin'] );
    }

    return $args;
}

add_filter( 'searchwp_live_search_query_args', 'my_ searchwp_live_search_query_args' );
```

**Comment by joemcgill** [comment]
Thanks @jchristopher. The filter code you added is not exactly right, because the original `$args` array passed to the filter looks like this:

```
$args = array(
					's'             => $query,
					'post_status'   => 'publish',
					'post_type'     => get_post_types( array(
							'public'   => true,
							'_builtin' => true,
							'exclude_from_search' => false
						) ),
				);
```

A filter that will work is this:

```
/**
 * Filter for live searching custom post types
 */
function my_filter_live_search( $args ) {
	if ( ! empty($args['post_type']) ) {
		$args['post_type'] = get_post_types( array(
							'public'   => true,
							'exclude_from_search' => false
						) );
	}

	return $args;
}
add_filter('searchwp_live_search_query_args', 'my_filter_live_search');
```

**Comment by jchristopher** [comment]
That's what I get for cowboy coding in a comment box! Thanks a ton @joemcgill

**Comment by jchristopher** [comment]
This was fixed in https://github.com/jchristopher/searchwp-live-ajax-search/commit/27b14c511bd8a5771e18f88c51169034c5b87294
