### ISSUE TITLE
How search categories?

### ISSUE THREAD

**Issue by Canopix** [jchristopher/searchwp-live-ajax-search#24]
Hello! :) 
I need seach only categories, not posts. 

I need the search return the titles of categories and link! But not posts!

It is possible?

**Comment by jchristopher** [comment]
This plugin is designed to search posts, if you're looking to search taxonomy terms you'd need to build something specifically to do that, or if you're using SearchWP you can use the Term Archive Priority extension to include taxonomy term archives in results: https://searchwp.com/extensions/term-archive-priority/

**Comment by Canopix** [comment]
Thanks, I've solved my issue with a list and JavaScript along with a search box.
I'm still interested in making a search only category in wordpress.
