### ISSUE TITLE
Live search works but widget does not.

### ISSUE THREAD

**Issue by LIBERTYmenu** [jchristopher/searchwp-live-ajax-search#25]
I get the ajax loaded content when using the standard search widget but not when using the Ajax supplied widget (returns to index.php when clicking search, but ajax works).

I have no idea how to fix this! It also was working a few weeks ago (testing live search on a dev site).

**Comment by jchristopher** [comment]
Hi there, I checked into this but can't seem to replicate the issue. Do you see the issue in Twenty Fifteen? Can you pass along a screencast of the issue? Will definitely open this back up if necessary!
