### ISSUE TITLE
Relevanssi Support

### ISSUE THREAD

**Issue by jasonblackdog** [jchristopher/searchwp-live-ajax-search#29]
Hello,
I currently have your plugin Version 1.1 (not the PRO version) and Relevanssi Premium Version 1.13.5 installed. When I search, the SearchWP does not return any results. If I disable Relevanssi Premium and try to search, then your plugin works but only returns items with the keyword in the title. Your plugin states it is compatible with Relevanssi but I cannot get it to work. How can I get these to work together? Do I have to purchase the pro version of your plugin? Any help would be greatly appreciated.

P.S.
I made sure the Relevanssi has indexed my pages:
-Documents in the index: 41
-Terms in the index: 907
-Highest post ID indexed: 283

**Comment by jchristopher** [comment]
No SearchWP is definitely not necessary. I don't have Relevanssi Premium but I will check out the free version when I can. 

Jonathan Christopher

**Comment by jasonblackdog** [comment]
Thanks Jonathan. If your pro version of the plugin **IS** compatible with Relevanssi Premium, then I have no problem purchasing the pro, please let me know. Just curious though, in your logs, how did you test to confirm that support for Relevanssi was added? In any case, thanks for the speedy reply and overall great plugin.

**Comment by jchristopher** [comment]
It's a totally separate relationship, SearchWP provides the same functionality as Relevanssi so they should never be active at the same time. I haven't looked into Relevanssi support in a long time so it may have changed something. I'll check when I can and update this. 

Jonathan Christopher

**Comment by jasonblackdog** [comment]
Hey Jonathan,
Just wanted to follow up on this. Any new info? Any help with this is greatly appreciated.

**Comment by jchristopher** [comment]
I haven't had a chance to dig in yet, no. I'll update here as soon as I have time to look into it. 

Jonathan Christopher

**Comment by jchristopher** [comment]
I ran a test with the free version of Relevanssi and it looks to work as expected. I don't have a copy of Relevanssi premium to test with, however. Perhaps reaching out to the developer of that plugin can shine some light on the issue? SearchWP Live Ajax Search is set up in the same way as Dave's Live WordPress Search and it seems like that developer and the Relevanssi developer have been in contact about integrating those two in the past, perhaps that will help?

For reference, this is how Relevanssi is integrated into SearchWP Live Ajax Search: https://github.com/jchristopher/searchwp-live-ajax-search/blob/master/includes/class-relevanssi-bridge.php

**Comment by yratof** [comment]
To reopen the same issue – Relevanssi Pro stops this plugin from working – was there a solution or a reason behind it?
