### ISSUE TITLE
Block plugin from going to the actual search results page

### ISSUE THREAD

**Issue by andywarren** [jchristopher/searchwp-live-ajax-search#30]
I have the plugin installed, and working great. What I want to do is block the plugin from going to a search results page and only display the ajaxed results. I do not have a submit button on the form, but if the user were to hit "enter/return" then they are taken to a new page where the search results are displayed. I do not want this to happen. Is there a way to block it? Thanks.

**Comment by andywarren** [comment]
Should have Googled first. Found the answer right here: http://stackoverflow.com/questions/895171/prevent-users-from-submitting-form-by-hitting-enter

Closing the comment, thanks!

**Comment by jchristopher** [comment]
Awesome!
