### ISSUE TITLE
Is it possible to limit the search result queries to specific categories?

### ISSUE THREAD

**Issue by scooterlord** [jchristopher/searchwp-live-ajax-search#31]
Hello, thanks for the wonderful plugin - already helps me heaps!

I have pages with custom queries and would like  to limit search to specific categories. I tried using  query_posts( 'cat=X' )  inside the search-results.php but had no luck. Is there any way to do it?

Moreover is it possible to use different search templates for different categories?

Thanks! Looking forward to your answer!

**Comment by jchristopher** [comment]
Yes, using the `searchwp_live_search_query_args` filter you can limit to your category: https://github.com/jchristopher/searchwp-live-ajax-search/blob/master/includes/class-client.php#L64
