### ISSUE TITLE
Results not reloading when input cleared and repopulated

### ISSUE THREAD

**Issue by jchristopher** [jchristopher/searchwp-live-ajax-search#32]
1. Perform search
2. Let results show
3. Clear input field
4. Immediately re-type search
5. Results don't show (loader just spins)

**Comment by pierrestoffe** [comment]
I'm experiencing the same issue, although it only occurs when the user is typing the query fast. If I re-type the query slowly, the results will show as expected.

I found that by removing the `this.last_string !== $.trim(e.currentTarget.value)` condition in maybe_search, things start to work as expected again.

**Comment by jchristopher** [comment]
Thank you!
