### ISSUE TITLE
New javascript property results_destroy_on_blur has no effect

### ISSUE THREAD

**Issue by hesselberg** [jchristopher/searchwp-live-ajax-search#33]
Hello,

Recently updated to version 1.1.4, and since then, I've been having issues with the results not getting destroyed.

Looking through the changesets I can see that 'results_destroy_on_blur' was introduced, and it should be  true on default. It does however not appear in the configuration object, nor does it seem like it's possible to change.

Can you either show me how exactly to set it properly, or is there in fact a bug where it isn't editable?

**Comment by jchristopher** [comment]
Good to go now, thank you!

**Comment by hesselberg** [comment]
Great! Thanks! :+1:
