### ISSUE TITLE
Engine not properly selected with multi instances

### ISSUE THREAD

**Issue by mdorchain** [jchristopher/searchwp-live-ajax-search#34]
Hi,

I observed that the engine is not always selected properly when using multiple instance. 
If only one form is defined, there is no issue. But when at least 2 are defined in the same page using different engine, it seems to only keep one engine for all the forms no matter how the engines have been defined.

This how I get to this result:

I have 2 separated search form instances using 2 different engines (default + supplemental).
Each engine is specified using data-swpengine in each form.
I defined a specific result template for each engine, just to be sure which engine is in use.

When making the search, I get results from the same engine, no matter what form I'm using.

Is there anything I forgot to do to avoid the confusion between the engines?

Thanks

Michael

**Comment by jchristopher** [comment]
Can you provide a link to the page with both search forms? If that needs to be kept private can you open a SearchWP support ticket and include the URLs?

**Comment by mdorchain** [comment]
Hi Jonathan,

Here is a sample url illustrating: http://pacific-lawyers.redstratus.com/test-search/.
One form is located in the ubermenu, the other in the page. However the location of the second form doesn't seem to matter.

I also attached the code used for the 2 search forms and the templates used in the child theme.

The search form in the ubermenu:

```
<div class="ubermenu-search">
<form id="search" role="search" method="get" class="ubermenu-searchform" action="">
<input type="text" placeholder="Search..." value="" name="s" class="ubermenu-search-input" data-swplive="true" data-swpengine="default">
<input type="submit" class="ubermenu-search-submit" value="">
</form>
</div>
```


The search form in the page:

```
<div class="ubermenu-search">
<form id="attorney-search" role="search" method="get" class="ubermenu-searchform" action="" style="width: 80%">
<input style="width: 100%" type="text" placeholder="Search..." value="" name="s" class="ubermenu-search-input" data-swplive="true" data-swpengine="attorneys">
</form>
</div>
```

To differentiate the engine, I gave them a specific heading.
Here are the templates used:

search-results.php:

```
<h4>Search Results</h4>
<?php if ( have_posts() ) : ?>
	<?php while ( have_posts() ) : the_post(); ?>
		<?php $post_type = get_post_type_object( get_post_type() ); ?>
		<div class="searchwp-live-search-result">
			<p><a href="<?php echo esc_url( get_permalink() ); ?>">
				<?php if ( has_post_thumbnail() ) : ?>
				<?php the_post_thumbnail( 'tt_post_icon' ); ?>
				<?php endif; ?>
				<span><?php the_title(); ?> (<?php echo esc_html( $post_type->labels->singular_name ); ?>) &raquo;</span>
			</a></p>
		</div>
	<?php endwhile; ?>
<?php else : ?>
	<p class="searchwp-live-search-no-results">
		<em><?php _ex( 'No results found.', 'swplas' ); ?></em>
	</p>
<?php endif; ?>
```

search-results-attorneys.php:

```
<h4>Attorney Search Results</h4>
<?php if ( have_posts() ) : ?>
	<?php while ( have_posts() ) : the_post(); ?>
		<?php $post_type = get_post_type_object( get_post_type() ); ?>
		<div class="searchwp-live-search-result">
			<p><a href="<?php echo esc_url( get_permalink() ); ?>">
				<?php if ( has_post_thumbnail() ) : ?>
				<?php the_post_thumbnail( 'tt_post_icon' ); ?>
				<?php endif; ?>
				<span><?php the_title(); ?> (<?php echo esc_html( $post_type->labels->singular_name ); ?>) &raquo;</span>
			</a></p>
		</div>
	<?php endwhile; ?>
<?php else : ?>
	<p class="searchwp-live-search-no-results">
		<em><?php _ex( 'No results found.', 'swplas' ); ?></em>
	</p>
<?php endif; ?>
```

So normally each form should use it's own engine and template for the results, but for any reason it doesn't behave that way.
Please let me know if you prefer me to open a ticket instead.

tnx

Michael
