### ISSUE TITLE
exclude results

### ISSUE THREAD

**Issue by Li-An** [jchristopher/searchwp-live-ajax-search#35]
Hello,
very interesting plugin - faster than the previous I used. I would love an option or hint to hide some results - archive page and so on.

**Comment by melriksdesign** [comment]
I added this to my themes functions file and it appears to have excluded these pages from my results.
/* Exclude pages from Search
https://wordpress.org/support/topic/exclude-a-few-pages-in-search-results

*/

function filter_where($where = '') {
	if ( is_search() ) {
		$exclude = array(27,42,34,35,41);
		for($x=0;$x<count($exclude);$x++){
		  $where .= " AND ID != ".$exclude[$x];
		}
	}
	return $where;
}
add_filter('posts_where', 'filter_where');

**Comment by Li-An** [comment]
I made a test and it does not seem to work.

**Comment by pixedelic** [comment]
This way works fine form me:

```php
add_filter('searchwp_live_search_query_args', 'filter_live_search');
function filter_live_search( $args ) {
    if ( class_exists('WooCommerce') )  { //in this way it displays only products if WooCommerce is active
        $args['post_type'] = 'product';
    } elseif ( ! empty($args['post_type']) ) {  //default behaviour
        $args['post_type'] = get_post_types( array(
            'public'   => true,
            'exclude_from_search' => false
        ) );
    }

    $hide_ids = array('24'); //to hide a particular post by ID or IDs
    $args['post__not_in'] = $hide_ids;

    return $args;
}
```

**Comment by Li-An** [comment]
Thanks. I will take a look.

**Comment by anagio** [comment]
@pixedelic do you have any other filters running against the main loop or with pre get posts? I'm using the code below trying to prevent post ID 5363 from showing in live results but it's not working. I'm quite sure that the args aren't using `post__in` within the class of the plugin which would conflict with `not__in`. 

`add_filter('searchwp_live_search_query_args', 'filter_live_search', 999);

function filter_live_search( $args ) {

    $hide_ids = array(5363); //to hide a particular post by ID or IDs
    $args['post__not_in'] = $hide_ids;

    return $args;
}`

**Comment by pixedelic** [comment]
Not sure to understand what you mean @anagio, sorry. Do you think it doesn't work if the theme has got other filters or if it doesn't have them?
However tried with a theme of mine where I have other filters for pre_get_posts (since I want to remove some pages both from live search and default search as well) and I also tried with TwentyFifteen and no plugins installed and it works fine in both cases.

**Comment by jchristopher** [comment]
Hi there, the solutions provided here should do the trick! Specifically https://github.com/jchristopher/searchwp-live-ajax-search/issues/35#issuecomment-176241798 using `post__not_in` will facilitate exclusion.
