### ISSUE TITLE
FR: Keyboard Support

### ISSUE THREAD

**Issue by davemoore24** [jchristopher/searchwp-live-ajax-search#37]
Great plugin! If possible, I would love to add keyboard support using up/down arrows for the dropdown if possible.

**Comment by jchristopher** [comment]
That'd be a great improvement, would love some help with that if anyone has time!

**Comment by jchristopher** [comment]
Thank you @geoffreycrofte https://github.com/jchristopher/searchwp-live-ajax-search/pull/66
