### ISSUE TITLE
PageView Tracking and Full Site Search

### ISSUE THREAD

**Issue by melriksdesign** [jchristopher/searchwp-live-ajax-search#40]
For anyone interested, I updated the search template to include a "Full Site Search" link with the search term embedded.  Other ajax searches have a link like this at the bottom. I also added virtual page tracking with google analytics (for those tracking site search).

Add this to search-results.php after the last php endif.

<?php //http://www.wpexplorer.com/customize-search-results-wordpress/ ?>
<?php $search_term = get_search_query(); ?>
<p class="full-search-link"><a href="/?s=<?php echo (str_replace(' ','+', $search_term)); ?>">Full Site Search</a></p>
	
	<?php //Google Analytics Tracking ?>
	<?php //https://support.google.com/analytics/answer/1012264?hl=en ?>
	<script>
	ga('send', 'pageview', '/?s=<?php the_search_query(); ?>')
	</script>

**Comment by jchristopher** [comment]
Thanks for this!
