### ISSUE TITLE
Possible to add a click here for more results link 

### ISSUE THREAD

**Issue by rtwlabs** [jchristopher/searchwp-live-ajax-search#42]
Setting up the plugin for a client and trying to work out how to add an option to the bottom of the live search results to tell people they can click through for more results. It might seem obvious to just hit enter  to do that but in testing people have though there was only x number of posts on the topic when there was obviously a lot more if they'd got to the search page.

I imagine this can be done with the custom templating just not sure on the appropriate reference to use to capture the search phrase entered to then pass to a link for them to click

**Comment by jchristopher** [comment]
Hi there, yes the best course of action would be to customize the results template to output a link exactly as you'd like: https://searchwp.com/extensions/live-search/#customizing-results

You can retrieve the search query with [`get_search_query()`](https://codex.wordpress.org/Template_Tags/get_search_query)

**Comment by rtwlabs** [comment]
Thanks @jchristopher for the life of me I couldn't' think of the right function to use to capture the query string used.

**Comment by rtwlabs** [comment]
Thinking on this and get_search_query() won't have a value until we hit enter as the ajax search is doing the looking up first so there's no value to return unless we hit enter to fire it no? I'd need to be able to pull the entered search term from the query that the plugin has used to lookup the details instead or have I just got myself all turned around?

**Comment by jchristopher** [comment]
Whoops, sorry about that, have a look at `$_REQUEST['swpquery']` for the value, which is what the plugin submits via AJAX

**Comment by rtwlabs** [comment]
Perfect that's the missing link I needed.

**Comment by jchristopher** [comment]
:+1:

**Comment by paulhastings0** [comment]
@rtwlabs Would you mind sharing the code that you used for your final solution? I'm working on a site and would like to do something similar. Thanks!
