### ISSUE TITLE
How get total found posts and search string in search-results.php

### ISSUE THREAD

**Issue by abombelli** [jchristopher/searchwp-live-ajax-search#43]
Hello

We would like to add a link after the found results (if there are more results then the ones returned via ajax), who points to the search result page.

Right now we have this, but need the value of total found posts and the used search value for the link.
```php
<?php if ( have_posts() ) : ?>
	<?php
			global $wp_query;
			$posts_per_page = $wp_query->query["posts_per_page"];
			$posts_found 	= $wp_query->query["found_posts"];
	?>
	<?php while ( have_posts() ) : the_post(); ?>
		<?php 
			$post_type = get_post_type_object( get_post_type() );
		?>
		<div class="searchwp-live-search-result">
			<p><a href="<?php echo esc_url( get_permalink() ); ?>">
				<?php the_title(); ?> (<?php echo esc_html( $post_type->labels->singular_name ); ?>)
			</a></p>
		</div>
	<?php endwhile; ?>
		<div class="searchwp-live-search-result">
			<?php if ($posts_found > $posts_per_page) { ?>
			<p class="more-results"><a href="<?php echo get_search_link( $query ); ?>">
				Show all results &raquo;
			</a></p>
			<?php } ?>
		</div>
<?php else : ?>
	<p class="searchwp-live-search-no-results">
		<?php _ex( 'No results found.', 'swplas' ); ?>
	</p>
<?php endif; ?>
```

Thanks for any help on this!

Cheers,
Aldo

**Comment by BrutsSergio** [comment]
$posts_per_page = $wp_query->query["posts_per_page"];
$posts_found    = $wp_query->found_posts;

**Comment by abombelli** [comment]
@BrutsSergio Thanks but $wp_query->found_posts returns the number of posts taking into account the limit in searchwp_live_search_posts_per_page.
What I am after is the total number of results found for the search.

**Comment by BrutsSergio** [comment]
$posts_per_page = $wp_query->query["posts_per_page"];   -> returns the number of posts taking into account the limit in searchwp_live_search_posts_per_page.

$posts_found = $wp_query->found_posts; -> total number of results found for the search.

I done same functional ;)

**Comment by mrchimp** [comment]
`posts_per_page` and `found_posts` are both 10 for me, which is the same as the global number of posts per page. If I run my own query by creating a new `SWP_Query` I get a total of 2182 results. Something isn't right.

**Comment by jchristopher** [comment]
In this case SearchWP isn't effectively overriding `$wp_query->found_posts` since it's calling SearchWP directly. Flagging this as a bug in this plugin, and unfortunately you can't really get around it unless you repeat the search and manually hook into the `searchwp_live_search_alter_results ` action fired by this plugin.
