### ISSUE TITLE
data swpparentel

### ISSUE THREAD

**Issue by anagio** [jchristopher/searchwp-live-ajax-search#44]
I see at line https://github.com/jchristopher/searchwp-live-ajax-search/blob/master/assets/javascript/source/searchwp-live-search.js#L76

An option to set a data attribute to insert the results in a parent element. Is this simply  `data-swpparentel="selector"`

selector being a valid jQuery element selector?

**Comment by jchristopher** [comment]
Yes that's right, that should do it!
