### ISSUE TITLE
Should this plugin work on mobile?

### ISSUE THREAD

**Issue by avizaz** [jchristopher/searchwp-live-ajax-search#46]
Hi,

This plugin is great and I was wondering if it should work on mobile as well?

It didn't work from the get go on mobile and I was wondering if this is something that should work, or that I should find a solution for it to work?

Thanks
Aviran

**Comment by jchristopher** [comment]
Yes it should, but your theme may be outputting a different form that isn't auto-enabled. Sometimes themes swap out forms at certain breakpoints.
