### ISSUE TITLE
issues with wmpl

### ISSUE THREAD

**Issue by mdorchain** [jchristopher/searchwp-live-ajax-search#48]
Hi,

I'm using live search in association with searchwp and wpml.
I noticed that live search returns the entries for all languages, while the regular search returns only entries for the current language selected.

Is there any reason why the live search would ignore the current language ?

Here is an example: http://pacific-lawyers.redstratus.com/zh-hans/?s=berman.

Thanks

Michael

**Comment by jchristopher** [comment]
Hi Michael,

As long as the WPML Integration extension is active everything should work as expected. If you're still having trouble please feel free to open a ticket on the Help tab of your SearchWP settings screen.
