### ISSUE TITLE
I keep getting this error searchwp_live_search_params is not defined

### ISSUE THREAD

**Issue by epicallan** [jchristopher/searchwp-live-ajax-search#49]
looking through the JS code i still don't see any place where `searchwp_live_search_params` is defined. Am i missing something obvious?

**Comment by jchristopher** [comment]
Is your template file calling both `wp_head()` and `wp_footer()`?

**Comment by epicallan** [comment]
Hi, I cant say for sure because i decided to eventually drop using the plugin. But  my guess is that it probably was.
