### ISSUE TITLE
Live search populates but search results page is empty

### ISSUE THREAD

**Issue by kevinrajaram** [jchristopher/searchwp-live-ajax-search#50]
Hello,

I've implemented the plugin using the 'data-swplive="true"' to my search form. Now whenever I begin typing in characters, the search populates with relevant searches but if I hit 'enter' to view the search results page, it is telling me it cannot find anything.

In the url of that page is: http://domainname.com/?search=termhere

**Comment by jchristopher** [comment]
You will need to customize your form `input` to have `name="s"` not `name="search"` in order for WordPress' search template to pick it up.

**Comment by kevinrajaram** [comment]
That worked wonderfully! It totally slipped my mind for not trying that! Thanks again for the help and for the super fast reply :)
