### ISSUE TITLE
not loading after ajax loaded page with smoothstate.js

### ISSUE THREAD

**Issue by they-are** [jchristopher/searchwp-live-ajax-search#53]
Hi there!

First of all thank you so much for this great Plugin. It took me a while until I got it working on WordPress Multisite & Relevanssi with multisite search. If you're interested in what to change to support this combination, please let me know.

For now I have another issue and still not able to fix it. I'm using smoothstate.js (https://github.com/miguel-perez/smoothState.js?files=1) a very useful preloading library which works great. Just the Ajax search is not working anymore if a page has been loaded by ajax. Any idea how I could solve this?

Best & thanks in advance!

Philipp

**Comment by jchristopher** [comment]
Hello, thank you for the kind words. With the library being referenced causing the issue when in place I would place the burden of integration on the part of that library as opposed to this plugin. I wouldn't be able to change the core plugin to accommodate one smooth scrolling library without having to support all smooth scrolling libraries.

That said, unfortunately I've never used that library so I don't have much feedback at this time. I'm hoping the author of the library might be able to provide some context as to why there's an incompatibility.
