### ISSUE TITLE
integrating live results into the search.php results

### ISSUE THREAD

**Issue by zreese** [jchristopher/searchwp-live-ajax-search#56]
I'm looking through the documentation and trying to figure out how best to do this. I'm using FacetWP and SearchWP in tandem. When the user is typing a query into the search form and they're on the search engine results page (search.php), I'd like to update the loop on the page rather than overlaying search-results.php.

Any chance this is a config option?

**Comment by jchristopher** [comment]
That would be something for FacetWP to implement in its search facet, but I'm not sure if it's supported at this time. SearchWP Live Ajax Search was designed and built to be a standalone keyword search attached to the search input itself.
