### ISSUE TITLE
Can't dequeue CSS

### ISSUE THREAD

**Issue by zreese** [jchristopher/searchwp-live-ajax-search#57]
Documentation says to use the standard `wp_dequeue_style()` function to remove stylesheets. That function fires just fine, but this stylesheet is still being loaded: `wp-content/plugins/searchwp-live-ajax-search/assets/styles/style.css`

There's also some CSS being injected into the page that I'd like to get rid of...

```
<style type="text/css">
	.searchwp-live-search-results {
		opacity:0;
		transition:opacity .25s ease-in-out;
		-moz-transition:opacity .25s ease-in-out;
		-webkit-transition:opacity .25s ease-in-out;
		height:0;
		overflow:hidden;
		z-index:9999;
		position:absolute;
		display:none;
	}

	.searchwp-live-search-results-showing {
		display:block;
		opacity:1;
		height:auto;
		overflow:auto;
	}

	.searchwp-live-search-no-results {
		padding:3em 2em 0;
		text-align:center;
	}
</style>
```
This is overriding my custom style.

**Comment by jchristopher** [comment]
There's a hook for that you can use: [https://searchwp.com/extensions/live-search/#searchwp_live_search_base_styles](https://searchwp.com/extensions/live-search/#searchwp_live_search_base_styles)

**Comment by zreese** [comment]
Yes, and I'm saying that's not working. It is still loading `wp-content/plugins/searchwp-live-ajax-search/assets/styles/style.css`

**Comment by jchristopher** [comment]
Hi @zreese that hook controls the inline CSS being injected, not the stylesheet

For reference: https://github.com/jchristopher/searchwp-live-ajax-search/blob/master/includes/class-form.php#L146-L183

**Comment by zreese** [comment]
Yes, but I need to remove the inline styles and dequeue style.css. Using `wp_dequeue_style( 'searchwp-live-search' );` doesn't seem to work. Maybe I'm misreading the documentation?

**Comment by jchristopher** [comment]
You would need to use both:

```php
// Prevent baseline SearchWP Live Ajax Search styles
add_filter( 'searchwp_live_search_base_styles', '__return_false' );

// Dequeue SearchWP Live Ajax Search stylesheet
add_action( 'wp_enqueue_scripts', function(){
	wp_dequeue_style( 'searchwp-live-search' );
}, 20 );
```

**Comment by zreese** [comment]
Oh, the priority! I didn't have priority set. That fixed it. Thank you so much!

**Comment by jchristopher** [comment]
Great, I'll be sure to update the docs!
