### ISSUE TITLE
Accessible live search

### ISSUE THREAD

**Issue by abombelli** [jchristopher/searchwp-live-ajax-search#59]
Hi Jonathan

The plugin is great and we us it in combination with SearchWP.

We need to build an accessible site and would like to use SearchWP Live Ajax Search.
The problem is, that the generated autocomplete dropdown is not accessible. Users using screen readers cannot tab through the results and hit enter to select them.

Here are some possible solutions:
[https://github.com/nico3333fr/jquery-accessible-autocomplete-list-aria](url)
[http://haltersweb.github.io/Accessibility/autocomplete.html](url)

Would be great if you could take this into your roadmap!

Thanks,
Aldo

**Comment by jchristopher** [comment]
Hi Aldo,

Yes, absolutely, fantastic suggestion!

**Comment by glueckpress** [comment]
Hi @jchristopher and @abombelli,
WP Rocket support rep here.

I’m currently testing SearchWP Live Ajax Search for an internal knowledge base for our support team, and lack of keyboard navigation as mentioned by Aldo above seems the single biggest issue for us so far. 

If we were to help out here, are there any starting points? The links provided above unfortunately are 404s meanwhile.

**Comment by glueckpress** [comment]
Actually, I just noticed my comment applies to https://github.com/jchristopher/searchwp-live-ajax-search/issues/37 as well. :)

**Comment by jchristopher** [comment]
Open to anything! The design of the plugin focuses on developer customizability, but if something can/should be rolled into the plugin itself that would be great!

**Comment by jon-ww** [comment]
@jchristopher I would also like to +1 this as I have client with the same needs. Looks like there is a PR from May that includes this: #66 . Any movement on this front?

**Comment by glueckpress** [comment]
A teammate of mine, @creativejuiz, apparently has made some progress on this issue. 🙏 
https://github.com/creativejuiz/searchwp-live-ajax-search/commits/master

**Comment by TimVevida** [comment]
Related, but no keyboard navigation:
The links inside the live seach popup are not the entire size of the search result. This reduces accessability for people with reduced motor skills, and increases ease-of-use overall.

Here is a screenshot showing the current clickable area:

![searchwp-live-search-clickable-area](https://user-images.githubusercontent.com/16288300/30848153-7e773fe6-a29e-11e7-96c0-4de95813a176.png)

**Comment by jchristopher** [comment]
Thank you @geoffreycrofte https://github.com/jchristopher/searchwp-live-ajax-search/pull/66
