### ISSUE TITLE
Adding event tracking

### ISSUE THREAD

**Issue by supervinnie40** [jchristopher/searchwp-live-ajax-search#60]
Hi there,

Thanks for the plugin. I'm a happy user.

If I might make a suggestion, why not add event tracking for the use in Analytics?
To make it a bit easier for you, it could look like this: 

From:
```
<div class="searchwp-live-search-result">
<p><a href="http://www.example.org/guides/how-to-apply-something/">How to apply something</a></p>
</div> 
```
Into:
```
<div class="searchwp-live-search-result">
<p><a onClick="ga('send', 'event', 'SearchWPform', 'click', 'how-to-apply-something');" href="http://www.example.org/guides/how-to-apply-something/">How to apply something</a></p>
</div> 
```

This would make it really easy (and awesome) to see the active results in Google Analytics.

**Comment by jchristopher** [comment]
Hi there, great suggestion! You would need to customize your results template to include this additional `onClick`, but that's easily done by taking advantage of the plugin's template loader:

https://searchwp.com/extensions/live-search/#customizing-results
