### ISSUE TITLE
How to change the output location to a different place in the dom

### ISSUE THREAD

**Issue by lmartins** [jchristopher/searchwp-live-ajax-search#61]
Hi,

First of all, thank you for this plugin. Im using it combined with you premium extension SearchWP and that one in particular is just awesome. 

Im looking for a way to customize where the live ajax search outputs the results in the dom. Any way I can achieve that?

Thank you.

**Comment by jchristopher** [comment]
Hi there! You can customize the parent element of the results by specifying a `data-swpparentel` attribute on your search input, e.g.

```html
<input type="text" name="s" id="s" data-swpparentel="#my-target-results-parent-id"/>
```

**Comment by lmartins** [comment]
Thanks @jchristopher 
I've went with a different route using the REST-API but SearchWP still ;)
