### ISSUE TITLE
Remove post type from live search results

### ISSUE THREAD

**Issue by verysiberian** [jchristopher/searchwp-live-ajax-search#62]
Hello! Thank you for this excellent plugin. I have noticed that with the twentyfourteen theme that live search results include the post type in parentheses. This is somewhat distracting and I don't think that the user needs to see it. I would appreciate any suggestions for removing the content. An example screenshot is attached.
<img width="1440" alt="screen shot 2017-02-23 at 12 06 09 pm" src="https://cloud.githubusercontent.com/assets/20424440/23272353/89ce1f22-f9c0-11e6-9e6e-b21ce0266375.png">

Best regards,
Rob

**Comment by jchristopher** [comment]
Hi Rob, the plugin has a template loader built in allowing you to completely customize how results are displayed. The docs and a walkthrough are available here:

https://searchwp.com/extensions/live-search/#customizing-results
