### ISSUE TITLE
Unable to config

### ISSUE THREAD

**Issue by QUT-BDA-MOOC** [jchristopher/searchwp-live-ajax-search#64]
An alert shows with "No valid SearchWP Live Search configuration found!" when trying to config with  "searchwp_live_search_configs" filter.

**Comment by jchristopher** [comment]
Can you share the code you're using?

**Comment by QUT-BDA-MOOC** [comment]
I've added the following to the functions.php:

`function my_searchwp_live_search_configs( $configs ) {
   $configs['default'] = array(
        'engine' => 'default',                      // search engine to use (if SearchWP is available)
        'input' => array(
            'delay'     => 500,                 // wait 500ms before triggering a search
            'min_chars' => 3,                   // wait for at least 3 characters before triggering a search
        ),
        'results' => array(
            'position'  => 'bottom',            // where to position the results (bottom|top)
            'width'     => 'auto',              // whether the width should automatically match the input (auto|css)
            'offset'    => array(
                'x' => 0,                   // x offset (in pixels)
                'y' => 5                    // y offset (in pixels)
            ),
        ),
        'spinner' => array(                         // powered by http://fgnass.github.io/spin.js/
            'lines'         => 10,              // number of lines in the spinner
            'length'        => 8,               // length of each line
            'width'         => 4,               // line thickness
            'radius'        => 8,               // radius of inner circle
            'corners'       => 1,               // corner roundness (0..1)
            'rotate'        => 0,               // rotation offset
            'direction'     => 1,               // 1: clockwise, -1: counterclockwise
            'color'         => '#000',          // #rgb or #rrggbb or array of colors
            'speed'         => 1,               // rounds per second
            'trail'         => 60,              // afterglow percentage
            'shadow'        => false,           // whether to render a shadow
            'hwaccel'       => false,           // whether to use hardware acceleration
            'className'     => 'spinner',       // CSS class assigned to spinner
            'zIndex'        => 2000000000,      // z-index of spinner
            'top'           => '50%',           // top position (relative to parent)
            'left'          => '50%',           // left position (relative to parent)
        )
    );
}
add_filter( 'searchwp_live_search_configs', 'my_searchwp_live_search_configs' );`

**Comment by QUT-BDA-MOOC** [comment]
Also if you add the filter and an empty function, so don't modify the config, it fails with the same error. The search input that is generated looks like this:

<input type="search" id="search-form-590293389d541" class="search-field" placeholder="Search …" value="" name="s" data-swplive="true" data-swpengine="default" data-swpconfig="default" autocomplete="off">

**Comment by lee25home** [comment]
Im actually seeing the exact same error. Using the config setup set up by the documentation.

**Comment by lee25home** [comment]
Solved the issue by directly editing the JSON in your footer (cpdata json ). You can add you configs in there for the engine to pick up. It might also be a problem with your get_footer function if not. (which I am not using - hence the error  for me ) 

Seems like it is working as documented.
