### ISSUE TITLE
Feature request: filter for front-end widget output

### ISSUE THREAD

**Issue by glueckpress** [jchristopher/searchwp-live-ajax-search#65]
@jchristopher Are there any objections against a PR that would wrap the [front-end output of the  widget](https://github.com/jchristopher/searchwp-live-ajax-search/blob/master/includes/class-widget.php#L23-L61) into a filter, so it could be customised?

**Comment by jchristopher** [comment]
Hi @glueckpress — can you share with me the benefit of that vs. writing your own Widget (using that class as a starting point)?

**Comment by glueckpress** [comment]
Gah, good point. Didn’t even think that far. 😇  Will close.

**Comment by jchristopher** [comment]
Cool! Yeah I think building your own Widget would apply here but wanted to make sure I wasn't missing anything. Thank you!
