### ISSUE TITLE
Show search result with page image (Thumbnail)

### ISSUE THREAD

**Issue by Champac** [jchristopher/searchwp-live-ajax-search#67]
Hi.
Is there a way to show the searchs results with the page associated image (in thumbnail) include with the page link ?

I also want to know how can i change the spinner color to white ?
Finally, how can i change the "no result found" text to white color ?

Thank a lot.

**Comment by alewolf** [comment]
Regarding thumbnails, have a look at this gist: https://gist.github.com/alewolf/1fe8e3b4cd3ceb8237ae2ffcd0282e32

**Comment by gr8shivam** [comment]
For showing the thumbnails, you can use the template that @alewolf suggested.

For customising the no result found text, you can add styles to the class `searchwp-live-search-no-results`

For example, for white coloured "no result found" text, add this to your css:-

```
.searchwp-live-search-no-results{
color:#fff;
}
```
