### ISSUE TITLE
Cannot set custom engine unless remove auto hijack forms

### ISSUE THREAD

**Issue by lmartins** [jchristopher/searchwp-live-ajax-search#69]
Hi, 

Just a very minor glitch, I was trying to set the default form search template to use a custom search engine using the data attribute `data-swpengine="catalogue"` but that was always being ignored by the plugin when activating the live search on that form.

I had to run the filter `add_filter( 'searchwp_live_search_hijack_get_search_form', '__return_false' );` and manually enable the live search with `data-swplive="true"`, only then it assumed the custom search engine for this form.

**Comment by jchristopher** [comment]
This should be all set but if not please open a new Issue thank you!
