### ISSUE TITLE
Ability to get search referrer ID

### ISSUE THREAD

**Issue by tombalev** [jchristopher/searchwp-live-ajax-search#70]
It would be nice to be able to access search referrer (post ID for example) of the page where the search was initialised. Could be easily done by modifying $_REQUEST values and including hidden input field, but it would be great to be able to do this automatically and just have access to this var throughout results.

**Access via filters**
`(
    [post_type] => any
    [post_status] => any
    [post__in] => Array
        (
            [0] => 5672
            [1] => 5670
            [2] => 5671
            ...
        )
    [orderby] => post__in
    [search_referrer] => 5563
    [posts_per_page] => 20
)`

**Access in template**
`$referrer = isset( $_REQUEST['search_referrer_page_id'] ) ? sanitize_text_field( $_REQUEST['search_referrer_page_id'] ) : '';`

**Comment by jchristopher** [comment]
I won't be able to tackle this issue, but PRs are welcome!
