### ISSUE TITLE
Template override for class-widget.php

### ISSUE THREAD

**Issue by prokopsdk** [jchristopher/searchwp-live-ajax-search#71]
Hi there!

I have the need to edit the output html from plugins/searchwp-live-ajax-search/includes/class-widget.php

Is it possible to make an override for this file? Copying it to my template dir as /template/searchwp-live-ajax-search/includes/class-widget.php does nothing for me.

Cheers

**Comment by jchristopher** [comment]
You can just create a new, separate, custom Widget using the bundled Widget as a starting point.
