### ISSUE TITLE
Position problem for search result when using sticky bar

### ISSUE THREAD

**Issue by prokopsdk** [jchristopher/searchwp-live-ajax-search#72]
Hi there!

When using a theme with a sticky bar, such as flatsome, there is a problem with repositioning on scroll.
The result for ordinary non-sticky header is ok.
The results for the sticky version repositions once on scroll but loses the position quickly afterwords. If the ajax reloads then it recomputes the position ok.

The search results for the default wordpress ajax results tracks the position of the menu fine.

Can you confirm there is a problem with the js respositioning?

https://imgur.com/SaVBb3C

Cheers

**Comment by jchristopher** [comment]
Support for sticky parent elements has not been tested, any PR would be welcome here as I will not be able to tackle that issue at the moment.

**Comment by lmartins** [comment]
It would be pretty nice if we had an option to provide what should be the parent element for the search results. That would likely solve this and other similar issues.

**Comment by jchristopher** [comment]
You can add `data-swpparentel="#myelement"` to your search input where `#myelement` is a CSS selector of the parent element.
