### ISSUE TITLE
Selected supplemental search engine is not used

### ISSUE THREAD

**Issue by flegfleg** [jchristopher/searchwp-live-ajax-search#73]
Hi, i hope this is the right place to ask this question. 
I am using **SearchWP**, **searchwp-live-ajax-search**, **searchwp-term-priority**.  

I want to search my custom post type "events", and display the event tags/taxonomies first. This is working with the non-ajax search, but NOT for the ajax search. Customizations (like the spinner color) i put in the configs-array are displayed, but the results are from the default search, not from my supplemental search engine in the backend, called "events".

Any help is appreciated! 
Thanks!

**search.php**

		<form action="" method="get">SEARCH
				  <fieldset>
					<legend>Supplemental Search</legend>
					<p>
					  <label for="searchwpquery">Search</label>
					  <input type="text" id="searchwpquery" name="searchwpquery" value="<?php echo esc_attr( $query ); ?>" data-swplive="true" data-swpconfig="events" data-swpengine="events" />
					</p>
					<p><button type="submit">Search</button></p>
				  </fieldset>
				</form>

**functions.php**

		/**
	 * SearchWP: Term Archive Priority
	 * https://searchwp.com/extensions/term-archive-priority/
	 */
	add_filter( 'searchwp_tax_term_or_logic', '__return_true' );

	// custom live search config
	function my_searchwp_live_search_configs( $configs ) {
		// override some defaults
		$configs['events'] = array(
			'engine' => 'events_search',                   // search engine to use (if SearchWP is available)
			'input' => array(
				'delay'     => 500,                 // wait 500ms before triggering a search
				'min_chars' => 3,                   // wait for at least 3 characters before triggering a search
			),
			'results' => array(
				'position'  => 'bottom',            // where to position the results (bottom|top)
				'width'     => 'auto',              // whether the width should automatically match the input (auto|css)
				'offset'    => array(
					'x' => 0,                   // x offset (in pixels)
					'y' => 5                    // y offset (in pixels)
				),
			),	
			'spinner' => array(                         // powered by http://fgnass.github.io/spin.js/
				'lines'         => 10,              // number of lines in the spinner
				'length'        => 8,               // length of each line
				'width'         => 4,               // line thickness
				'radius'        => 8,               // radius of inner circle
				'corners'       => 1,               // corner roundness (0..1)
				'rotate'        => 0,               // rotation offset
				'direction'     => 1,               // 1: clockwise, -1: counterclockwise
				'color'         => '#ff0000',          // #rgb or #rrggbb or array of colors
				'speed'         => 1,               // rounds per second
				'trail'         => 60,              // afterglow percentage
				'shadow'        => false,           // whether to render a shadow
				'hwaccel'       => false,           // whether to use hardware acceleration
				'className'     => 'spinner',       // CSS class assigned to spinner
				'zIndex'        => 2000000000,      // z-index of spinner
				'top'           => '50%',           // top position (relative to parent)
				'left'          => '50%',           // left position (relative to parent)
			),
		);
		return $configs;
	}
	add_filter( 'searchwp_live_search_configs', 'my_searchwp_live_search_configs' );
	
	// enable custom live search config
	function my_searchwp_live_search_get_search_form_config() {
		return 'events';
	  }   
	add_filter( 'searchwp_live_search_get_search_form_config', 'my_searchwp_live_search_get_search_form_config' );
	
	// prevent use of custom config elsewhere
	add_filter( 'searchwp_live_search_hijack_get_search_form', '__return_false' );

**Comment by jchristopher** [comment]
Hi @flegfleg as a SearchWP customer you're entitled to direct support via the Help tab on the SearchWP settings screen within your WordPress admin. Please open a ticket there and we can troubleshoot the issue. Thank you!
