### ISSUE TITLE
Limit to a post_type param

### ISSUE THREAD

**Issue by benjaminniess** [jchristopher/searchwp-live-ajax-search#75]
Hi,

I have 2 search forms in a single page. The first one is generic (all public post types) and the second one needs to search in a single post type. Is there a chance to have an extra optional data-post_types param in the search form that would limit the autocompletion to one or several given post types?

Thanks.

**Comment by jchristopher** [comment]
My first reaction is that would be too feature-specific and instead an adaptation of the `searchwp_live_search_query_args` hook would be better applied. I won't have much time to research this issue but any suggestions via PR are welcome, thanks!
