### ISSUE TITLE
Customize different search results for different engines

### ISSUE THREAD

**Issue by lmartins** [jchristopher/searchwp-live-ajax-search#76]
Hi,

I'm using two different search engines on the same page (one global one specialised), and I would like to customize the way results are displayed for each case. 

I've noticed that the results box is being added via Javascript, with no options to have a way to distinguish the boxes other that the ID attribute, which is this case I'm not sure it would work as I'm seeing different values for the local and remote installs.

Any way to achieve this?

Thanks!

**Comment by jchristopher** [comment]
This sounds related to #75

**Comment by wittich** [comment]
Same issue here. I think #75 is more about what should be looked up.

As @lmartins, I would like to have different formatting for each search results. But the result list is only reachable over its unique id. I think it would be nice if you could set a class for the result list via the data attribute at the input field. Or set different search-results templates for the default the same search engine.

**Comment by wittich** [comment]
BTW I solved it with adding a data attribute with the desired class name (eg. `data-class="special-format"`) to the input field. Then I use the little script add the class to the result div:

```
$(function () {
    var plugin_name = "searchwp_live_search";  
    $('input[data-swplive="true"]').each(function () {
        $(this).on('click', function () {
            var styleClass = $(this).attr('data-class');
            // set class(s)
            if ($.data(this, "plugin_" + plugin_name)) {
                $.data(this, "plugin_" + plugin_name).results_el.addClass(styleClass);
            }
        });
    });
});
```
