### ISSUE TITLE
Set div for results

### ISSUE THREAD

**Issue by tchernitskaya** [jchristopher/searchwp-live-ajax-search#77]
Hello! Help me, please!
I need to show search results in specific div of my theme.
I set id to my div `<div id="searchwp-live-search-results">`
But results still pop-up in default container.
What should I do to put results into my div?
How to set this div?
Any help is appreciated!

**Comment by tchernitskaya** [comment]
I mean, how to position search results into my div?
Please, any help!

**Comment by jchristopher** [comment]
Please see the docs about the parent element: https://searchwp.com/extensions/live-search/
