### ISSUE TITLE
Not activating at all

### ISSUE THREAD

**Issue by vladmalik** [jchristopher/searchwp-live-ajax-search#81]
Downloaded plugin to plugins/searchwp-live-ajax-search folder
Activated plugin in WP dashboard
Nothing happens when I type (no spinner, no results)
Special class is present (also tried the get_form function)

What could be the issue?

Look for hidden #searchform element on goodui.org/blog

Thanks!

**Comment by jchristopher** [comment]
It looks like your template may not be calling `wp_footer()` — can you check for that?
