### ISSUE TITLE
Bad possition on various pages

### ISSUE THREAD

**Issue by CreativForm** [jchristopher/searchwp-live-ajax-search#84]
I have problem that search results comming in the various possitions on the page and can't stick to the search form.

[Image 1](http://prntscr.com/jny90q)
[Image 2](http://prntscr.com/jny9k5)

Maby is site padding or something else but this is anoying. We also buy a pro version.

Can you help? Thanks!

**Comment by jchristopher** [comment]
The images have since been removed. If you are a SearchWP customer please use the Support tab of the SearchWP settings screen to open a ticket to receive direct support. Thank you!
