### ISSUE TITLE
Conditionally filter live search results

### ISSUE THREAD

**Issue by tobybenjamin** [jchristopher/searchwp-live-ajax-search#86]
I'm using the `searchwp_live_search_query_args` to filter my search results by post type (semi-successfully), but have been unable to conditionally apply this filter.

Using the example below, I'd expect that the search would be limited to `post`s only on the 404 page, but the filter does not apply. If I change the conditional to `!is_404()` or remove the conditional entirely, the filter applies everywhere.

I've also tried using `is_page_template('404.php')` in place of `is_404()` with no success.

Any thoughts on how I can apply this filter conditionally based on my location within the site? 

```
  add_filter('searchwp_live_search_query_args', 'filter_live_search', 999);
  function filter_live_search( $args ) {
    if( is_404() ) { $args['post_type'] = 'post'; }
    return $args;
  }
```

**Comment by ffoodd** [comment]
Hi there, 
What about:
```php
if ( is_404() ) {
  add_filter('searchwp_live_search_query_args', 'filter_live_search', 999);
}
```
Shouldn't it work?

**Comment by jchristopher** [comment]
Yes that should work!
