### ISSUE TITLE
Add class to body tag when live searching?

### ISSUE THREAD

**Issue by joeblackburn** [jchristopher/searchwp-live-ajax-search#88]
I may just be missing it, but is there a hook to add a class to the body when an active live search is happening? I'm trying to find a way to hide pre-search results when the live search is returning results, but I can't figure out is there is a hook available to make that happen.

**Comment by jchristopher** [comment]
There are two events that are triggered when searches are performed:

```javascript
jQuery(document).on('searchwp_live_search_start', function() {
    console.log('Search has started');
});
```

```javascript
jQuery(document).on('searchwp_live_search_complete', function() {
    console.log('Search has completed');
});
```
