### ISSUE TITLE
Conflict with SearchWP Term Archive Priority

### ISSUE THREAD

**Issue by lstoyanoff** [jchristopher/searchwp-live-ajax-search#90]
Hi, I am using **SearchWP 2.9.14** + **SearchWP Term Archive Priority 1.1.4** on **WordPress 4.9.8**. I have installed **SearchWP Live Ajax Search 1.3.1** and initialised it on a custom form:

```
<form action="" method="get">
	<div class="form__body">
		<input
			type="search"
			name="searchwpquery"
			value=""
			data-swplive="true"
			data-swpengine="supplemental_engine"
			placeholder="<?php _e( 'Search', 'app' ); ?>"
		/>

		<input type="submit" name="" value="<?php _e( 'Search', 'app' ); ?>" />
	</div><!-- /.form__body -->
</form>
```

There is an error with Term Archives in the Results.

![capture](https://user-images.githubusercontent.com/35492381/43823434-b29c5f20-9af7-11e8-9245-2c714b09b48d.JPG)

**Comment by jchristopher** [comment]
Thank you for the report! Term Archive Priority has been updated to 1.1.5 to resolve this issue.
